@startuml
title Activity Diagram - CRUD Dosen

partition "<b>Dosen</b>" {
  start
  :Login ke sistem;
  :Masuk menu Data Dosen;
  :Pilih aksi (Create / Read / Update / Delete);
}

' === CREATE ===
if (Create?) then (ya)
    partition "<b>Dosen</b>" {
      :Isi form dosen:\n- Name\n- Email\n- Password\n- Password_confirmation\n- NIDN\n- Fakultas;
    }
    partition "<b>Sistem</b>" {
      :Validasi data;
      :Simpan ke tabel Dosen;
    }
    partition "<b>Dosen</b>" {
      :Konfirmasi berhasil;
    }


elseif (Read?) then (ya)
  partition "<b>Sistem</b>" {
    :Ambil daftar dosen \n(Name, Email, Password, Password_confirmation, NIDN, Fakultas);
  }
  partition "<b>Dosen</b>" {
    :Lihat data dosen;
  }

elseif (Update?) then (ya)
  partition "<b>Sistem</b>" {
    :Ambil daftar dosen \n(Name, Email, Password, Password_confirmation, NIDN, Fakultas);
  }
  partition "<b>Dosen</b>" {
    :Pilih Dosen;
    :Edit data dosen \n(Name, Email, Password, Password_confirmation, NIDN, Fakultas);
  }
  partition "<b>Sistem</b>" {
    :Validasi data;
    :Update tabel Dosen;
  }
  partition "<b>Dosen</b>" {
    :Konfirmasi berhasil;
  }

elseif (Delete?) then (ya)
  partition "<b>Sistem</b>" {
    :Ambil daftar dosen \n(Name, Email, Password, Password_confirmation, NIDN, Fakultas);
  }
  partition "<b>Dosen</b>" {
    :Pilih dosen;
  }
  partition "<b>Sistem</b>" {
    :Hapus record dari tabel Dosen;
  }
  partition "<b>Dosen</b>" {
    :Konfirmasi berhasil;
  }

endif

partition "<b>Dosen</b>" {
  stop
}
@enduml
