@startuml
title Activity Diagram - Penilaian dan Absensi(Dosen/Asisten)


partition "<b>Dosen/Asisten</b>" {
    start
  :Login ke sistem;
  :Masuk menu Penilaian & Absensi;
  :Pilih aksi (Penilaian/Absensi);
}

if (Penilaian) then (ya)
    partition "<b>Sistem</b>" {
        :Tampilkan jenis penilaian;
    }
    partition "<b>Dosen/Asisten</b>" {
        :Pilih jenis penilaian ;
    }
    if (Weekly) then (ya)
        partition "<b>Sistem</b>" {
            :Tampilkan data 
            mahasiswa;
            :Tampilkan parameter 
            nilai;
        }
        partition "<b>Dosen/Asisten</b>" {
            :Pilih mahasiswa;
            :Input nilai mingguan (Weekly)
            & Catatan;
        }
        partition "<b>Sistem</b>" {
            :Validasi data;
            :Simpan ke 
            tabel Nilai;
            :Konfirmasi nilai
            berhasil disimpan;
        }
    elseif (UTS/UAS) then (ya)
        partition "<b>Sistem</b>" {
            :Tampilkan data
            mahasiswa;
            :Tampilkan parameter nilai;
        }

        partition "<b>Dosen/Asisten</b>" {
            :Pilih mahasiswa;
        }

        if (Absen Cukup) then (ya)
            partition "<b>Dosen/Asisten</b>" {
                :Input nilai UTS/UAS;
            }
            partition "<b>Sistem</b>" {
                :Validasi data;
                :Simpan ke 
                tabel Nilai;
                :Konfirmasi nilai 
                berhasil disimpan;
            }
        else (tidak)
            partition "<b>Sistem</b>" {
                :Absen tidak cukup;
            }

            partition "<b>Dosen/Asisten</b>" {
                :Notifikasi absen 
                tidak cukup;
            }
        endif
    else if (Proyek) then (ya)
        partition "<b>Sistem</b>" {
            :Tampilkan data
             kelompok Proyek;
        }
        partition "<b>Dosen/Asisten</b>" {
            :Pilih proyek;
            :Input nilai Proyek
            & Catatan;
        }
        partition "<b>Sistem</b>" {
            :Validasi data;
            :Simpan ke tabel Nilai;
            :Konfirmasi nilai
             berhasil disimpan;
        }
    
    endif

elseif (Absensi) 

    partition "<b>Sistem</b>" {
        :Tampilkan form 
        input tanggal;
    }

    partition "<b>Dosen/Asisten</b>" {
        :Pilih tanggal;
    }

    partition "<b>Sistem</b>" {
        :Tampilkan data 
        mahasiswa;
    }

    partition "<b>Dosen/Asisten</b>"{
        :Pilih mahasiswa;
        :Input absensi 
        (Hadir, Sakit, Izin, Alfa) 
        & Keterangan;
    }

    partition "<b>Sistem</b>" {
        :Simpan ke tabel Absensi;
        :Konfirmasi absensi 
        berhasil disimpan;
    }

endif

' ==== Tambahan Validasi Nilai Akhir ====
partition "<b>Sistem</b>" {
    :Tampilkan rekap nilai akhir;
}
partition "<b>Dosen</b>" {
    :Review & Validasi nilai akhir;
}
if (Nilai Oke?) then (ya)
    partition "<b>Dosen/Asisten</b>" {
        stop
    }
else (tidak)
    partition "<b>Asisten</b>" {
        :Revisi nilai sesuai instruksi dosen;
    }

endif

partition "<b>Dosen/Asisten</b>" {
    stop
}

@enduml
